### ISSUE TITLE
MongoDB authentication failed.

### ISSUE THREAD

**Issue by simechiang** [balderdashy/sails-mongo#142]
My MongoDB opens the Auth certification, but I do not know how to set in sails-mongo. Error information is as follows:
{ [MongoError: auth fails] name: 'MongoError', code: 18, ok: 0, errmsg: 'auth fa
ils' }
...
TypeError: Cannot call method 'createCollection' of null.

I hope someone can help me.Thanks!

**Comment by pdavid0** [comment]
I'm having the same error in prod. The password I use contains a ' ) '.
```
Error: Failed to connect to MongoDB.  Are you sure your configured Mongo instance is running?
 Error details:
{ [MongoError: auth failed] name: 'MongoError', ok: 0, errmsg: 'auth failed', code: 18 }
    at _createError (/usr/share/nginx/html/dubrise-server/node_modules/sails-mongo/lib/adapter.js:98:23)
    at /usr/share/nginx/html/dubrise-server/node_modules/sails-mongo/lib/adapter.js:101:13
    at /usr/share/nginx/html/dubrise-server/node_modules/sails-mongo/lib/connection.js:25:20
    at /usr/share/nginx/html/dubrise-server/node_modules/sails-mongo/node_modules/mongodb/lib/mongodb/mongo_client.js:460:15
    at process._tickDomainCallback (node.js:486:13) { [Error: Failed to connect to MongoDB.  Are you sure your configured Mongo instance is running?
```

Using : 

```
mongo -u user -p '12346)1234' ip:27017/mDB --authenticationDatabase admin
```

works. My question is : where do I start looking ?

**Comment by srinathrajappa** [comment]
Hi im new to mongodb while db connection string throwing this error pls help
W NETWORK  Failed to connect to x.x.x.x:27017 after 5000 milliseconds, giving up.
E QUERY    Error: couldn't connect to server x.x.x.x:27017 (x.x.x.x), connection attempt failed

**Comment by randallmeeker** [comment]
@srinathrajappa have you checked your password for the special characters listed above?

**Comment by boris-lapouga** [comment]
Did you guys managed to fix this so far? I've encountered the very same error with latest sails-mongo version.
