### ISSUE TITLE
Update MongoDB native to version 2?

### ISSUE THREAD

**Issue by bearkids** [balderdashy/sails-mongo#233]
The native driver provided CRUD API (insertOne, insertMany, updateOne, updateMany, removeOne, removeMany, bulkWrite, findOneAndDelete, findOneAndUpdate, findOneAndReplace)
in version 2.0.

It would be great if those functions are included in sails.
Many thanks.

**Comment by andyhu** [comment]
+1

**Comment by listepo** [comment]
+1

**Comment by arndtjenssen** [comment]
+1

**Comment by dinana** [comment]
+1

**Comment by felipecm** [comment]
+1

**Comment by andypham** [comment]
+1

**Comment by mgenev** [comment]
I agree. Updating the driver should be relatively simple, but that won't give you the functions unless you send them through the `native` methods. The adapter has to be extended to support these new functions as well.

**Comment by danscan** [comment]
The main reason I want to update to 2.0 is because the codebase of 1.4.26 is hideous.  When I have the pubsub hook enabled in production, it crashes my whole app because of this ugliness:

https://github.com/mongodb/node-mongodb-native/blob/V1.4.26/lib/mongodb/connection/base.js#L246

**Comment by andypham** [comment]
Also, updating mongo native driver to 2.0 will help fix a bug that I'm facing now in production for readPreference setting. The readPreference is always set to primary. See commit 
https://github.com/mongodb/node-mongodb-native/commit/bd289549c069d44de152fb49f614483c9324c98a#diff-af7f90364fd34f588f43f92c13a92ab6

**Comment by mgenev** [comment]
Does anybody foresee any breaking changes which may not get caught by the unit tests?

**Comment by andypham** [comment]
I ran the test with mongo 2.0.27 and it failed at
1) adapter "before all" hook:
     Uncaught TypeError: Cannot read property 'socketTimeoutMS' of undefined

**Comment by mgenev** [comment]
Considering the comments could choose a 2 step process in which we gain the benefit of upgrading the by updating and fixing breaking changes in the first PR and then adding support for the new methods in a 2nd PR.
Thoughts?

**Comment by devinivy** [comment]
Yeah, it would be great if we updated all dependencies for a first PR.

**Comment by andypham** [comment]
@mgenev I like your suggested approach.

**Comment by rasekar2000** [comment]
+1

**Comment by mattapperson** [comment]
+1

**Comment by mattapperson** [comment]
@mgenev this works for me. My main reason for needing to update is to get support for the wiredtiger

**Comment by andypham** [comment]
Update: I updated sails-mongo to mongo native 2.0 and fixed all the tests. It passed on my machine running mongo version 2.6.5, but failed in travis running mongo 2.4.12. Any of you guys know how to update mongo version for travis. Pull request is here https://github.com/balderdashy/sails-mongo/pull/260

**Comment by listepo** [comment]
+1

**Comment by andypham** [comment]
OK. So i ran the test again on my machine using mongo version 2.4.12 and all tests passed. I'm stumped right now why the test cases are failing in travis.

**Comment by listepo** [comment]
@andypham, node 0.8 must be remove, sails js "node": ">= 0.10.0",

**Comment by andypham** [comment]
@listepo Thanks. Will do that.

**Comment by mgenev** [comment]
I'm not seeing a way to tell Travis to install mongo 3.0, i'm going to ask in  issue I think

**Comment by dmarcelino** [comment]
> @andypham, node 0.8 must be remove, sails js "node": ">= 0.10.0"

There's already a PR for that: #255.

**Comment by andypham** [comment]
I ran the test on both mongo 2.6.5 and 3.0.2 and all tests passed.

**Comment by dmarcelino** [comment]
@andypham, by "all tests" does that include the "greaterThan" tests? Because currently the sails-mongo integration tests always exit with 0 giving the false impression all tests pass when that is not true: [example (line 374)](https://travis-ci.org/balderdashy/sails-mongo/jobs/31966981#L374).

PR  #255 addresses that little nuisance and once it's merged test results should be more reliable.

**Comment by andypham** [comment]
@dmarcelino Yes, I fixed that. https://github.com/balderdashy/sails-mongo/pull/260

**Comment by dmarcelino** [comment]
Ah nice, good man! :+1:

**Comment by dmarcelino** [comment]
I still see a test not passing on #260 travis build though... "Association Interface Has Many Association create nested associations() with single level depth and objects mixed with ids should create a new customer and payment association"
https://travis-ci.org/balderdashy/sails-mongo/jobs/58984575#L203

Is this because of waterline core or something?

**Comment by andypham** [comment]
@dmarcelino I ran the tests again using both mongo 2.6.5 and 3.0.2 and I'm not seeing that failure. Once we get travis to run mongo 2.6.5 or mongo 3.0.2, we can then see if that failure still exist.

**Comment by mgenev** [comment]
I looked at Travis and there is no apparent way to update mongo, hence my issue linked above...

**Comment by andypham** [comment]
@mgenev I found this googling. Should we give it a try?
http://www.theodo.fr/blog/2014/12/choose-a-specific-mongodb-version-in-travis/

**Comment by dmarcelino** [comment]
I see, travis seems to be on Mongo 2.4 if I understood travis-ci/travis-ci#2246 correctly.

@andypham, can you try adding that do the .travis.yml and see it improves things? The only disadvantage I can think of is slowing down the build a bit but I think it may be worth it.

**Comment by andypham** [comment]
@dmarcelino OK. I will give it a shot. Fingers cross.

**Comment by dmarcelino** [comment]
Thanks ;)

**Comment by andypham** [comment]
@tjwebb Any new update for this pull request #260? A few of folks here really need this fix? I appreciate your help. Thanks.

**Comment by andypham** [comment]
Thank you all for working with me on this issue in our first pull request to supporting mongo native 2.0. Especially, thank you to @dmarcelino @particlebanana for getting the pull request in. Great work guys!

**Comment by andypham** [comment]
@particlebanana Can you publish a new version to npm with the latest change in master branch? Thanks.

**Comment by particlebanana** [comment]
@andypham just published `0.10.7` thanks for your work!

**Comment by andypham** [comment]
@particlebanana Thank you for the quick response. Glad that I'm able to contribute.
