### ISSUE TITLE
If there's no result from a query, shall we return empty result instead of throwing an error?

### ISSUE THREAD

**Issue by andyhu** [balderdashy/sails-mongo#236]
Error should mean something went wrong. When there's no records, nothing is wrong. I haven't heard of any software working like this. So can we change it?

**Comment by formula1** [comment]
+1

**Comment by devinivy** [comment]
Can you give an example of how this might occur and what the specific error message is?  I've not seen this issue!

**Comment by formula1** [comment]
Actually, I couldn't reproduce this error. I'll delete my plus one since I wrote it mystified that that was an issue in the first place.

**Comment by dmarcelino** [comment]
Closing this as inactive, please re-open with an example of when this happens or a failing test. Thanks
