### ISSUE TITLE
Connection time out

### ISSUE THREAD

**Issue by Josebaseba** [balderdashy/sails-mongo#246]
Hi @particlebanana,

Some times I find this error in my sails app:

Details:  MongoError: connection to [my_connection.bla_bla.com:port] timed out

It happens in the first request that some (few) users make to the application, I take the session from Redis and I check if the user is still activated/desactivated or if it exists in the DB, then I make some stuff depending on the answer I have. Actually every day I've more than 10.000 sessions or connections and the error appears more or less 20 times every two days.

I ask to my mongodb hosting company about this error and that's the answer that they give me:

---

This can sometimes happen when using the default timeout settings that come with some drivers. Some drivers set this value too low and connections time out before they have a chance to be established. This can especially be a problem if your application is hosted outside of AWS or in another region.

To fix it, we suggest using a timeout of 30 seconds. You should also upgrade your drivers to the latest available version as some older drivers didn't set timeouts properly.

---

So that's ok, and digging in this repo code to find how can I configure the mongo timeout I've found that the timeout config option is inside the sockets connection config:

https://github.com/balderdashy/sails-mongo/blob/master/lib/adapter.js#L62

and then set it as sockets option:

https://github.com/balderdashy/sails-mongo/blob/master/lib/connection.js#L101

But:

socketTimeoutMS: 5000 // For sockets, How long a send or receive on a socket can take before timing out.

connectTimeoutMS: 5000 // For connection, How long a connection can take to be opened before timing out.

You can check more info [here](http://mongodb.github.io/node-mongodb-native/driver-articles/mongoclient.html)

Maybe I'm in the wrong way and actually we can configure the connection timeout. I'll appreciate any help here, I can collaborate with a pull-request but first I need some feedback.

Thanks!! If we fix this issue my Sails app will work with 0 errors...

Pd: This is related with: https://github.com/balderdashy/waterline/issues/773

**Comment by particlebanana** [comment]
@Josebaseba the config flag here: https://github.com/balderdashy/sails-mongo/blob/master/lib/adapter.js#L62 is just a default. If you pass in your own it should be overriding it. Let me know if you aren't able to override the config.

**Comment by Josebaseba** [comment]
But the connectTimeoutMS flag isn't a socketOption, it should go next to ssl or auto_reconnect flags.

In the adapter.js:
```javascript
      // Server Options
      ssl: false,
      poolSize: 1,
      connectTimeoutMS: 5000, // Here out of the sockets option
      socketOptions: {
        noDelay: false,
        keepAlive: 0,
        socketTimeoutMS: 5000
      },
      auto_reconnect: false,
      disableDriverBSONSizeCheck: false
```

That in the connection.js: https://github.com/balderdashy/sails-mongo/blob/master/lib/connection.js#L97

```javascript
connectionOptions.server_options = {
    readPreference: this.config.readPreference,
    ssl: this.config.ssl,
    connectTimeoutMS: this.config.connectTimeoutMS, // It should go here
    poolSize: this.config.poolSize,
    socketOptions: this.config.socketOptions, // No inside socketOptions as a sockets config attribute
    auto_reconnect: this.config.auto_reconnect,
    disableDriverBSONSizeCheck: this.config.disableDriverBSONSizeCheck
  };
```

Sorry if I'm not explaining the problem in a clean way... and thanks!

**Comment by luofan189** [comment]
I am experiencing the same issue. Any update on this? Thanks!

**Comment by Josebaseba** [comment]
I was totally wrong saying that the connectionTimeoutMS should go in a different place, sorry for that @particlebanana was totally right. To avoid this error check this configuration:

```javascript
'mongodb-production': {
    module: 'sails-mongo',
    host: 'mymongourl.com',
    port: 1234567,
    user: 'cooluser',
    password: 'pass',
    database: 'mydb',
    socketOptions: {
      connectTimeoutMS: 30000,
      socketTimeoutMS : 30000
    }
  }
```
This error isn't a SailsJS error, it happens with Mongo applications that the DB and the app are hosted in different places.

I think that this config fixed the error but I'm waiting to be totally sure that the error is not going to happen again (the last week goes with 0 errors so i'm pretty sure that it will work for you too).

**Comment by luofan189** [comment]
Great, @Josebaseba . I will give a try today to see if it fixes my app or not. Btw, what about the pool size, do I just add it as the top level attribute as host and port? The default pool size is 1 and would like to config a bigger value for my app.

**Comment by Josebaseba** [comment]
Yes, it should look like this:
```javascript
'mongodb-production': {
    module: 'sails-mongo',
    host: 'mymongourl.com',
    port: 1234567,
    user: 'cooluser',
    password: 'pass',
    database: 'mydb',
    socketOptions: {
      connectTimeoutMS: 30000,
      socketTimeoutMS : 30000
    },
    poolSize: 5
  }
```
If you check that the error is fixed for you too, write it here and I'll close the issue. Thanks!

**Comment by Josebaseba** [comment]
Definitely this config fixed the error, I'm going to close this issue. Thanks!
