### ISSUE TITLE
Returns only one record with Sails > blouprints.js > defaultLimit: 4294967295

### ISSUE THREAD

**Issue by jstrika** [balderdashy/sails-mongo#247]
If in Sails  > blouprints.js > defaultLimit: 4294967295, GET (find action) and no limit defined, returns only one record. If "limit" is defined, it is working as expected for main records, but then if "Populate" on collection atribute is also returning only 1 record.

 Soution is to change defaultLimit: 50, and then we are getting 50 records, as well 50 nested records after populate

**Comment by tjwebb** [comment]
Is this a real issue? Set your limit to something realistic. Most users won't be trying to incite an integer overflow.
