### ISSUE TITLE
Embedded association creates duplicate data

### ISSUE THREAD

**Issue by dylanbathurst** [balderdashy/sails-mongo#252]
I started an issue in the Waterline project: https://github.com/balderdashy/waterline/issues/892

I was directed to post it here instead as Mongo and SQL might preform differently. Any help or clarity is much appreciated.

**Comment by randallmeeker** [comment]
can you show your models for verification

**Comment by dylanbathurst** [comment]
Solved here: https://github.com/balderdashy/waterline/issues/892#issuecomment-84156943
