### ISSUE TITLE
sails-mongo takes too long to load collections on initialization

### ISSUE THREAD

**Issue by dmarcelino** [balderdashy/sails-mongo#253]
As pointed out by @mkeremguc in balderdashy/waterline#904:

> sails lift --silly logs the last model as silly: Registering modeluserin Waterline (ORM) and waits there about 6-7 minutes using 100% CPU then goes to next hook (grunt) and finishes lifting.

> using:
> nodejs v0.10.37
> sails v.0.11.0
> waterline v0.10.19
> sails-mongo v0.10.6

> some debug and i found where it takes time:
node_modules/sails-mongo/lib/collection.js line 358: collectionDef = _.cloneDeep(definition);
in _parseDefinition function, it deep clones the definition object which is a circular structure that has waterline attribute that has collections and schema attributes. that definition is just a key of waterline.collections attribute itself. so deep cloning that big circular structure takes time on every model and makes orm hook take too long. removing clone and just referencing like collectionDef = definition fixed the issue. however, this needs feedback for a permanent fix on sails-mongo adapter. lemme know if i should open this issue in sails-mongo

**Comment by mkeremguc** [comment]
also it would be good if we do feedback and fix this issue permanently very soon. thanks

**Comment by mkeremguc** [comment]
can we get some feedback from collaborators ?

**Comment by dmarcelino** [comment]
cc: @particlebanana, @randallmeeker

**Comment by mkeremguc** [comment]
i think this should also be high priority imo. here is the line that deep-clones circular structure https://github.com/balderdashy/sails-mongo/blob/master/lib/collection.js#L358

**Comment by victorbadila** [comment]
+1 for high priority on this
