### ISSUE TITLE
Waterline + sails-mongo (but no sails). Disconnecting from mongo

### ISSUE THREAD

**Issue by bbohling** [balderdashy/sails-mongo#259]
I'm trying to create some jobs that support my sails services. Instead of using the entire sails framework for the jobs I thought I would use only the sails pieces I needed in addition to cron. This slimmed down my needs to just waterline and sails-mongo (for the most part).

I can get this setup to work except I cannot disconnect/teardown my connection from mongo so the script never ends. Not a huge deal, but will (I would imagine) eventually cause some memory problems.

If I'm mimicking the [raw example](https://github.com/balderdashy/waterline/tree/master/example/raw) (except using sails-mongo) how would I _close_ the mongo connection? I have tried hard-coding the [teardown logic](https://github.com/balderdashy/sails-mongo/blob/master/lib/adapter.js#L124) with no luck.

**Comment by ertrzyiks** [comment]
Same here, i use just waterline as orm and my gulp task using mongodb adapter never ends. I think i've found solution (it works for me &trade;), created pull request and meanwhile I use package from my fork.
