### ISSUE TITLE
sails is not responding after sails-mongo 0.11

### ISSUE THREAD

**Issue by mkeremguc** [balderdashy/sails-mongo#269]
sails is not responding to any req when using sails-mongo 0.11.
when using 0.10.8, no problem. so that would probably mean issue is related to #260 

using mongodb 3.0.2

**Comment by antipodeman** [comment]
+1

**Comment by aradnom** [comment]
Yup.  Looks a connection issue, if you bump the socket timeout up it will work until the initial connection drops, then it just never reconnects.  0.10.8 works fine.

**Comment by devinivy** [comment]
This is very likely related to the "destroyed topology" referenced in #266.  Both are connection issues.

**Comment by mahasen** [comment]
Having the same issue with sails 0.11 + sails-mongo 0.11. Dropped sails-mongo version to 0.10.8 and it works. I'm using mongo 3.x

**Comment by xm1999** [comment]
+1

**Comment by dmarcelino** [comment]
v0.11.2 released today fixes this. Please re-open if still experiencing this issue after the update.
