### ISSUE TITLE
Confirming accurate usage for sails-mongo versions...

### ISSUE THREAD

**Issue by irlnathan** [balderdashy/sails-mongo#271]
Howdy,

I made a pull request to change the readme to:

Use sails-mongo v0.11.x if you are using Mongo > v2.4.5.  Use sails-mongo v0.10.x if you are using Mongo <= v2.4.5.

I'm trying to do a quick screencast and I'd like to confirm that the above verbiage is accurate.  Can anyone confirm this or edit it to make it accurate?

Thanks!

**Comment by dmarcelino** [comment]
> Use sails-mongo v0.10.x if you are using Mongo <= v2.4.5.

**Or using Mongo 3.0**, taking into account https://github.com/balderdashy/sails-mongo/issues/266#issuecomment-98203817 and #269...

**Comment by dmarcelino** [comment]
@irlnathan, v0.11.2 released today should fix this permanently.
