### ISSUE TITLE
Connections fail after few minutes, no errors or debug info

### ISSUE THREAD

**Issue by mxrguspxrt** [balderdashy/sails-mongo#275]
I run in production mode with sails-mongo adapter on localhost.

For few minutes, everything runs works, but then server does not give answer. No info can be read from logs.

console.log('Quering', finder); // this is executed always
finder.exec(function(err, datapoints) {
  console.log('Query ended', err, datapoints); // this is executed only first minutes

If i would run "watch 'wget http://myservice/endpoint?query'" then service would work ok for hours. Hosting at azure. Not sure, from where and why whatkind of timelimits apply.    

sails -v
0.11.0
node -v
v0.10.37

**Comment by devinivy** [comment]
Can you check your version of sails-mongo?

**Comment by devinivy** [comment]
Please try setting `socketOptions.socketTimeoutMS` to `0` in your configuration, and let us know if that helps!  See #276 #266.

**Comment by devinivy** [comment]
See #277 for a proposed fix.

**Comment by alexbaumgertner** [comment]
Same problem, 
sails: 0.11.0  
node 0.12.2  
sails-mongo 0.11.0  

Thanks @devinivy, for https://github.com/balderdashy/sails-mongo/pull/277 it fixed :)

**Comment by dmarcelino** [comment]
v0.11.2 released today fixes this. Please re-open if still experiencing this issue after the update.
