### ISSUE TITLE
find({ select: [] }) is broken

### ISSUE THREAD

**Issue by dmarcelino** [balderdashy/sails-mongo#281]
In balderdashy/waterline-adapter-tests#71 I've added SELECT modifier tests (`find({ select: [] }) `) but unfortunately sails-mongo is breaking those tests: https://travis-ci.org/balderdashy/waterline-adapter-tests/jobs/62718504#L545

We need to fix this issue to bring sails-mongo on par with the other adapters.

cc: @andypham, @particlebanana, @tjwebb, @devinivy, @mgenev

**Comment by mgenev** [comment]
this is how waterline chooses which fields to deliver and it fails in mongo?

**Comment by dmarcelino** [comment]
Precisely!

**Comment by dmarcelino** [comment]
Fixed via #292.
