### ISSUE TITLE
sails-mongo 0.11.2 unique validation not working!

### ISSUE THREAD

**Issue by luisincrespo** [balderdashy/sails-mongo#290]
I'm using sails 0.11 and sails-mongo 0.11.2 adapter.

I have a user model with a nickname, and I want the nickname to be unique among every user. I specify the attribute as unique like this:

    nickname: {
       type: 'string',
       unique: true
    }

It is not working, I can add two users with the same nickname without a problem!!

**Comment by devinivy** [comment]
Was your original collection created by Waterline, or did you add Waterline to an existing collection?  Currently Waterline can only enforce indexes if it created the collection.  Here's the relevant code sails-mongo uses to deal with unique indices: https://github.com/balderdashy/sails-mongo/blob/1cfd3539bb7c29b5a2583c739a9cfc618a454f99/lib/collection.js#L403

**Comment by luisincrespo** [comment]
Yep I created the collection through waterline.

**Comment by alexandrepage** [comment]
Is there a fix for this issue?

**Comment by alexandrepage** [comment]
I dont know if it can help anyone. But when i run sails in production the mongo index keys that are use for the unique validation are not created. But when i deploy sails normally (dev mode) the index keys gets created.

**Comment by devinivy** [comment]
That's because in production, sails does not let you rebuild your collections.  It set migrate to `safe`.  See: https://github.com/balderdashy/sails-docs/blob/master/concepts/ORM/model-settings.md .  If your question feels unanswered, we can re-open this issue.

**Comment by luisincrespo** [comment]
If I manually drop the database, and then run the sails app again, it creates the pertinent collections but with no indexes for unique attributes.

**Comment by devinivy** [comment]
The collection will be created simply by trying to insert into it: http://docs.mongodb.org/manual/reference/method/db.collection.insert/#create-collection .  This doesn't mean that waterline actually set the collection up itself.

**Comment by luisincrespo** [comment]
Then how do I force waterline to set up indexes?. Or am I forced to set up my indexes manually?

**Comment by devinivy** [comment]
Waterline should create indexes when it's initialized if your migration strategy is `alter`, `drop`, or `create` on a model.  However, none of those migration strategies can be used in production because they're generally not sophisticated/safe enough, and sails ensures that you don't use any of them in production.  Here's the migration docs: https://github.com/balderdashy/waterline-docs/blob/5cc4b64207a8cb8e81c53358c7d6024e26e02147/models/configuration.md#migrate

**Comment by luisincrespo** [comment]
Ok got it!. So your recommendation would be to manually set up mongo indexes if I'm in production?

**Comment by devinivy** [comment]
Yep!
What I do when I want to build a production DB for the first time, which is a little hacky, is launch my application in a development mode to get waterline to build the database with indexes, etc.  This is only acceptable because the assumption is that I don't have any data to lose yet :P  After that, I write manual migrations.

**Comment by luisincrespo** [comment]
Ok I get it!... Thanks for your help!!. 

Best!

**Comment by devinivy** [comment]
Sure thing :)

**Comment by gayanhewa** [comment]
Adding the unique index creates the index on mongodb side , but there is no validation message given if we are using blueprint methods with a model. Any idea how to handle this situation ? Without the server hangs.

```
Unhandled rejection [Error (E_UNKNOWN) Encountered an unexpected error] Details:  WriteError({"code":11000,"index":0,"errmsg":"insertDocument :: caused by :: 11000 E11000 duplicate key error index: user-service.users.$username_1  dup key: { : \"gayan123\" }","op":{"username":"gayan123","email":"gayan123@mailinator.com","password":"$2a$10$IW5gor2a6qMj3SXzcePmRu8yUXDrDmlj/R4PRADa9lofjxsKPQVg6","first_name":"Neomal","createdAt":"2015-09-10T18:10:49.699Z","updatedAt":"2015-09-10T18:10:49.699Z","_id":"55f1c7a96627e58061c7c914"}})

```

The error on mongodb side is valid but , why doesn't it get translated to sailsjs validation compatible format ?

**Comment by didil** [comment]
I've created a hook module that ensures indexes are created in all environments https://github.com/didil/sails-hook-mongo-auto-index . Hope it helps , suggestions are welcome
