### ISSUE TITLE
Model query callbacks not happening

### ISSUE THREAD

**Issue by diegoaguilar** [balderdashy/sails-mongo#300]
I'm using Sails built in models and it's ORM to perform MongoDB queries and operations. The problem I got is that, for some query methods,it's callback is never being called. The DB operation gets done, but callback won't come up. Following code snippet is model querying  part of a controller method for an API, that's why I'm using a `response` object.

So, I've read [Sails docs](http://sailsjs.org/#!/documentation/reference/waterline/models/update.html) and it seems I'm actually doing as it's supposed to, but it wont' work.

By won't work, I mean callback it's not being executed, for example, in code snippet below, I can never see *Should happen*, and then any response is sent back to client, a 502 timeout is reached at client side.

      LineUp.update({ id: request.param('id') },
                    { players: [], budgetLeft: 60000000 }).
      exec(function (err, lineup) {
        console.log("Should happen");
        return err ? response.send(500) : response.json(lineup);
      });

Another example:

```
LineUp.update({id: lineupId}, foundLineUp).
  exec(function (err, saved) {
    console.log("Update Lineup cb");
    return err ? response.send(500, JSON.stringify(err)) : response.send(202, saved.toJson());
  });
```

I've posted an stackoverflow question where I explain details of how I've experienced these issues.

## Found when it's failing.

**This will fail when it actually does a modification.**

So anytime a match is made, eventhough modification at database is performed, callaback is not being triggered.  If not match is got, callback is being executed.

I've tested this with out mongodb module at package.json with 0.11.2, 0.10.6 and 0.10.8 versions of sails-mongo and find the same issue. I'm not sure yet if it's because of Mongo version or a mix of sails-mongo and mongodb modules versions.

I'm using `native` to cope with this issue and this way it's working as expected.

**Comment by devinivy** [comment]
Where does your mongo database live– on the same machine as your web server or elsewhere?  I wonder if, given how inconsistent the error seems to be, you're actually just running into network trouble!  The query could be hanging.  Do you have any non-default connection configuration options, including any timeout options?

**Comment by diegoaguilar** [comment]
I've tested this in two distinct Mongo installs at laptops and an AMI Ubuntu on EC2 instance. I will check soon against a MongoLab instance which is 2.4 because I remember I tested against it and had not such problems.

But, as my edit states, **it happens when a match is got**, if update/mongo gets not a match for first argument, it won't hang.

**Comment by diegoaguilar** [comment]
@devinivy And errors were not inconsistent or on an irregular basi, it's just I was blindly testing against not matching queries.

**Comment by devinivy** [comment]
[Here](https://github.com/balderdashy/sails-mongo/blob/master/lib/collection.js#L192) are the guts of the adapter's `update` method.  You can see it does go through a process of finding and updating entries.  But I don't see any glaring issues with callbacks being called.  This would be a good place to debug to see where the issue arises.

**Comment by diegoaguilar** [comment]
So, you mean that sails-mongo adapter is supposed to have a `updateMany` method? OR, it should be implementing `mongodb`'s one?

**Comment by devinivy** [comment]
I meant the latter– internally to the adapter we should be using `updateMany` rather than `update`.

**Comment by tjwebb** [comment]
@andypham do you think this might have something to do with the driver upgrade?

**Comment by andypham** [comment]
@tjwebb I'm not sure. I can take a look during my free time later today and respond back with my finding.

**Comment by japel** [comment]
@tjwebb it has probably something to do with the driver upgrade.
A colleague of mine tested yesterday using npm shrink to change the version.
This is what he changed:
```
├─┬ sails-mongo@0.11.2
│ ├── async@0.8.0
│ ├── lodash@2.4.2
│ ├─┬ mongodb@2.0.39 // changed from 2.0.40 to 2.0.39
│ │ ├── es6-promise@2.1.1
│ │ ├─┬ mongodb-core@1.2.6 // changed from 1.2.9 or newer to 1.2.6
│ │ │ ├── bson@0.4.8 // changed from 0.4.11 or newer to 0.4.8
│ │ │ └─┬ kerberos@0.0.12
│ │ │   └── nan@1.8.4
│ │ └─┬ readable-stream@1.0.31
│ │   ├── core-util-is@1.0.1
│ │   ├── inherits@2.0.1
│ │   ├── isarray@0.0.1
│ │   └── string_decoder@0.10.31
│ ├─┬ waterline-cursor@0.0.5
│ │ └── async@0.9.2
│ └── waterline-errors@0.10.1
```
After those changes he claims it worked again.

**Comment by devinivy** [comment]
Here are some relevant excerpts from the changelog for mongodb and mongodb-core.

https://github.com/mongodb/node-mongodb-native/blob/2.0/HISTORY.md#2040-07-14-2015
https://github.com/christkv/mongodb-core/blob/master/HISTORY.md#127-07-16-2015

Notably, in mongodb-core 1.2.7 there were refactors related to `getmore`.  If there's a well-defined bug we can file with the mongo project, that would be wonderful.

**Comment by robgrimball** [comment]
Just a note that for my issue #331 I effectively made the exact same changes to my shrinkwrap file and that was what resolved my issues as well.  So I am guessing the two are related.

**Comment by devinivy** [comment]
It would be nice to allow sails-mongo to continue accepting patches!  Can someone try the latest 2.0.43 release of mongodb?  It uses a new version to mongodb-core.  Also, how will we know this is fixed without a failing test?  It's a problem that's apparent, but a bit "fuzzy" to detect.  My fear is locking-down the driver version then it never getting opened-up again.

Lastly, is there a well-defined bug to file with mongodb or mongodb-core?

**Comment by japel** [comment]
@devinivy I could try using latest, but weirdly as it sounds, npm shrinkwrap is not showing mongodb as a dependency anymore

**Comment by devinivy** [comment]
Ah, yes– I meant master.  I thought it was already released since it was in the changelog.

**Comment by japel** [comment]
As stated in #324 using mongodb 2.0.42 my symptoms seem to go away
@diegoaguilar would you try yours with mongodb 2.0.42? either using npm shrinkwrap
or 
- normal npm install
- then deleting node_modules folder inside sails-mongo folder
- editing sails-mongo package.json for the dependencies to read:
```
"dependencies": {
    "async": "~0.8.0",
    "lodash": "~2.4.1",
    "mongodb": "2.0.42",
    "waterline-cursor": "~0.0.5",
    "waterline-errors": "~0.10.0"
  },
```

**Comment by robgrimball** [comment]
Same here, using mongodb 2.0.42 seems to clear up the problems I was having as well.

**Comment by devinivy** [comment]
PR posted: #332

**Comment by devinivy** [comment]
Merged!

**Comment by diegoaguilar** [comment]
Sorry I didn't reply on time, so these issues are fixed now with last Sails version, right?

**Comment by devinivy** [comment]
The latest version of this adapter should have this issue resolved– not sure if sails enforces a version for your adapters in any way, but I don't think that it does.
