### ISSUE TITLE
Correctly close connections on teardown

### ISSUE THREAD

**Issue by cheplv** [balderdashy/sails-mongo#306]
Current Issues with close db connections on teardown (#259, #264) not properly closes connections when connection name is null.

**Comment by devinivy** [comment]
Should the method allow you to not specify a connection name?  I wonder about that.  How are you using `teardown`?

**Comment by cheplv** [comment]
https://github.com/balderdashy/sails/blob/master/lib/hooks/orm/index.js#L244

In sails orm hook teardown function removes connections by adapters.

**Comment by devinivy** [comment]
Fair enough!  Looks good.  We should doc this.

**Comment by devinivy** [comment]
Resolved by #315.
