### ISSUE TITLE
Expire a document using Time To Live native functionality of mongoDb.

### ISSUE THREAD

**Issue by SudoPlz** [balderdashy/sails-mongo#311]
I leave that for others in case they need it in the future..

What I did in order to expire my documents in my server was,
in the boostrap code of my sails server (in a file that runs ONCE when the server goes up) I added the following function:
```javascript
function mongoDbSetTTLOnTokenCollection(next){

    sails.models.token.native(function (err, tokenCollection) {     //this allows us to run custom queries on mongodb, token is my collection but yours can be named anything
        sails.log.verbose('About to init ttl on mongo natively.');

        tokenCollection.dropIndexes(function(){     //I use that command to UPDATE the ttl property in case I've changed it.
            tokenCollection.createIndex({"createdAt": 1},           //then I create the ttl property with my own expiration time
//Oh and don't mind the number 1 after createdAt, thats just a placeholder, makes no difference.
                {expireAfterSeconds: 1200}, //that is 20 minutes till it expires
                function (error, data) {
                return next();
            });
        });
    });
}
```

From now on ANY document you create in the token collection will expire in 20 minutes.

In case someone needs its, this is my Token (waterline) Model:
```javascript
'use strict';
var _ = require('lodash');


var Token
    = {
    schema: true,
    identity: 'token',
    attributes: {

        issuedToken: {
            type: 'string',
            required: true
        },

        // Created timestamp as moment object
        createdAtObject: function() {
            var moment = (this.createdAt && this.createdAt != '0000-00-00 00:00:00')
                ? sails.services['date'].convertDateObjectToUtc(this.createdAt) : null;
            return moment;
        }
    }
};

module.exports = Token;
```

**Comment by lennym** [comment]
Since this was one of the top google results when I was solving the same problem myself...

I've taken @SudoPlz's code above, and used it as the basis for a hook which will do the above automatically if models have a `tt'` property configured. 

https://www.npmjs.com/package/sails-hook-ttl

Since it's my first attempt at writing plugins for Sails, and I've only been working with Sails generally for a few weeks, I'd be very grateful for any feedback, or obvious pointers where I've gone wrong.
