### ISSUE TITLE
One to one association not populating correctly

### ISSUE THREAD

**Issue by ryanwilliamquinn** [balderdashy/sails-mongo#320]
When populating, assessments are being attached to the wrong survey.  

Here is the expected scenario
```
sails> Survey.findOne('55ce1256faec6ffb2a01496b').populate('assessment').exec(console.log)
undefined
sails> null { student: '55ce1213faec6ffb2a014798',
  assessment:
   { survey: '55ce1256faec6ffb2a01496b',
     student: '55ce1213faec6ffb2a014798',
     format: 'online-learning',
     resultData:
      { score: 100,
        preparedness: 'Fully Prepared',
     createdAt: '2015-08-14T16:08:15.116Z',
     updatedAt: '2015-08-14T16:08:15.116Z',
     id: '55ce126ffaec6ffb2a014980' },
  surveyStructure: '55ce1213faec6ffb2a0147a3',
  createdBy: '55ce1216faec6ffb2a01492b',
  completed: true,
  answerCount: 20,
  createdAt: '2015-08-14T16:07:50.696Z',
  updatedAt: '2015-08-14T16:08:12.463Z',
  id: '55ce1256faec6ffb2a01496b' }
```
Here is an example where it is populating the wrong assessment:
```
sails> Survey.findOne('55ce1540ebf895852ece3ae6').populate('assessment').exec(console.log)
undefined
sails> null { student: '55ce1213faec6ffb2a014799',
  assessment:
   { survey: '55ce1256faec6ffb2a01496b',  // note that the survey id is not the same as the id we entered into the findOne query
     student: '55ce1213faec6ffb2a014798',
     format: 'online-learning',
     createdAt: '2015-08-14T16:08:15.116Z',
     updatedAt: '2015-08-14T16:08:15.116Z',
     id: '55ce126ffaec6ffb2a014980' },
  surveyStructure: '55ce1213faec6ffb2a0147a3',
  createdBy: '55ce1216faec6ffb2a014926',
  completed: true,
  answerCount: 20,
  createdAt: '2015-08-14T16:20:16.476Z',
  updatedAt: '2015-08-14T16:20:32.871Z',
  id: '55ce1540ebf895852ece3ae6' }
sails> Survey.findOne('55ce1256faec6ffb2a01496b', console.log)
undefined
sails> null { student: '55ce1213faec6ffb2a014798',
  surveyStructure: '55ce1213faec6ffb2a0147a3',
  createdBy: '55ce1216faec6ffb2a01492b',
  completed: true,
  answerCount: 20,
  createdAt: '2015-08-14T16:07:50.696Z',
  updatedAt: '2015-08-14T16:08:12.463Z',
  id: '55ce1256faec6ffb2a01496b' }
```

This same behavior occurs if you run `Survey.find().populate()`, every survey is populated with a single assessment instance.

The relevant part of the models look like you would expect them to:

```
// Survey.js
    "attributes": {
        "assessment": {
            "model": "assessment"
        },

// Assessment.js
        attributes: {

                student: {
                        model: 'student'
                },

                survey: {
                        model: 'survey'
                }
          },
```

sails mongo version 0.11.2

**Comment by particlebanana** [comment]
Waterline doesn't have true 1-1 associations. In your model above each attribute with a `model` property will have a foreign key set on it. So when you populate a survey it will fill in the assignment with whatever foreign key value it has set.

So your records will end up like this:

```javascript
// Survey
{ _id: abc123, assessment: foo123 }
```

Now when you call `Survey.findOne({ id: 'abc123' }).populate('assessment')` you get the survey with the assessment values for `foo123`.

So if you check your database for the survey record with id `55ce1540ebf895852ece3ae6` it should have a key named `assessment` with a value of `55ce126ffaec6ffb2a014980`

**Comment by ryanwilliamquinn** [comment]
In mongo, there is no `assessment` key on the `survey`.  `survey` has an assessment key: 
```
\\ survey
db.survey.find(ObjectId("55ce1540ebf895852ece3ae6"))
{ "_id" : ObjectId("55ce1540ebf895852ece3ae6"), 
  "surveyStructure" : ObjectId("55ce1213faec6ffb2a0147a3"), 
  "createdBy" : ObjectId("55ce1216faec6ffb2a014926"), 
  "completed" : true, "answerCount" : 20, 
  "student" : ObjectId("55ce1213faec6ffb2a014799"), 
  "createdAt" : ISODate("2015-08-14T16:20:16.476Z"), 
  "updatedAt" : ISODate("2015-08-14T16:20:32.871Z") }

\\ assessment
> db.assessment.find(ObjectId("55ce126ffaec6ffb2a014980"))
{ "_id" : ObjectId("55ce126ffaec6ffb2a014980"), 
  "survey" : ObjectId("55ce1256faec6ffb2a01496b"), 
  "student" : ObjectId("55ce1213faec6ffb2a014798"),  
  "createdAt" : ISODate("2015-08-14T16:08:15.116Z"), 
  "updatedAt" : ISODate("2015-08-14T16:08:15.116Z") }
```

**Comment by particlebanana** [comment]
Given this model there will be a key named assessment if you have set a relationship:

```javascript
// Survey.js
module.export = {
    "attributes": {
        "assessment": {
            "model": "assessment"
        }
}
```

Which would be set by doing something like this:

```javascript
Survey.create({ name: 'my-cool-survey', assessment: 'abc123'; })
```

If you never added an assessment to that record and calling `Survey.find().populate('assessment')` returns a record for it then that's a huge problem but we have that stuff tested pretty well and I don't know of other related issues to that.

**Comment by mcodev1** [comment]
Hey @particlebanana 

I'm experiencing this problem at multiple locations in our app and all of them involve calling `.populate`, and I'm not sure what could be causing it. If we're doing something wrong that could cause this to happen let me know! I know @ryanwilliamquinn mentioned that at one point he might try to isolate this in a vanilla Sails project, but in the meantime I'll dump out everything in our app that might be relevant here. (`[...]` = trimmed for readability)

CC @devinivy @ryanwilliamquinn @tjwebb 

A `Student` creates a `Survey` based on a `SurveyStructure`, and then completes it, which creates an `Assessment` and links that `Assessment` to both their `Survey` and their `Student` document.

#### api/models/Student.js
```js
module.exports = {

    "schema": true,
    "attributes": {
        "ipAssessment": {
            "model": "assessment"
        },
        [...]
    }
};
```

#### api/models/Survey.js
```js
var Promise = require('bluebird');
var RequireAttributes = require("../services/RequirementService").modelAttributes;
var AssessmentService = require("../services/AssessmentService");

module.exports = {

    "schema": true,
    "attributes": {
        "student": {
            "model": "student"
        },
        "assessment": {
            "model": "assessment"
        },
        "surveyStructure": {
            "model": "surveystructure"
        },
        "completed": {
            "type": "boolean",
            "defaultsTo": false
        },
        "answers": {
            "collection": "answer",
            "via": "survey"
        },
        "answerCount": {
            "type": "integer",
            "defaultsTo": 0
        }
    },

    "obtainAssessment": function(surveyId, options, cb) {

        if(_.isFunction(options)) {

            cb = options;
            options = null;
        }

        options = options || {};

        Promise.all([Assessment.findOne({survey: surveyId}), Survey.findOne(surveyId)
            .populate("answers", { "sort": "sort asc" })
            .populate("surveyStructure")])
            .spread(function(assessment, survey) {

                if(options.force || !assessment) {

                    AssessmentService.assess(survey, function(err, results) {

                        if(err) {
                            cb(err);
                            return;
                        }

                        survey.assessment =  assessment || {};

                        survey.assessment.survey = survey.id;
                        survey.assessment.student = survey.student;
                        survey.assessment.format = survey.surveyStructure.assessmentType;
                        survey.assessment.resultData = results;

                        survey.save(cb);
                    });
                }
                else {
                    cb(null, survey);
                }
            })
            .catch(cb);
    },

    "afterUpdate": function(survey, cb) {

        // Mark completed, get assessment async if necessary.
        Survey.findOne(survey.id)
            .populate("surveyStructure")
            .then(function(survey) {

                // If the survey became completed, mark it as such.
                if(!survey.completed &&
                    (survey.answerCount == survey.surveyStructure.questionCount)) {

                    survey.completed = true;
                    survey.save(cb);

                    // If the survey thinks it's completed but it's not, tell it otherwise.
                }
                else if(survey.completed &&
                    (survey.answerCount != survey.surveyStructure.questionCount)) {

                    survey.completed = false;
                    survey.save(cb);
                }
                else {

                    cb();
                }

            })
            .catch(cb);
    },

    // Require fields upon create, ensure consistent relationships.
    "beforeCreate": function(values, cb) {
        if(!values.createdBy) {
            return cb();
        }

        var self = this;
        User.findOne(values.createdBy)
        .then(function(result) {
            values.student = result.student;

            var requiredAttrs = [
                "student",
                "surveyStructure"
            ];

            RequireAttributes(requiredAttrs, values, self.adapter.identity, cb);
        })
        .catch(cb);
    }
};
```

#### api/models/Assessment.js
```js
module.exports = {

    "schema": true,
    "attributes": {
        "student": {
            "model": "student"
        },
        "survey": {
            "model": "survey"
        },
        [...]
    }
};
```

#### api/controllers/AssessmentController.js
```js
[...]
    "getInterestProfile": function(req, res) {

        User.findOne({
            "id": user
        })
        .populate("student")
        .then(function(userResult) {
            Student.findOne({
                "id": userResult.student.id
            })
            .populate("ipAssessment")
            .then(function(studentResult) {
                return res.json(studentResult);
            })
            .catch(function(err) {
                return res.serverError(err);
            });
        })
        .catch(function(err) {
            return res.serverError(err);
        });
    },
[...]
```

This returns the following:
```js
{
  "ipAssessment": {
    [...]
    "student": "55ce47fe015310754372d279", // Student ID (Assessment's)
    "id": "55d35010afb8db570b7c3e57" // Assessment ID
  },
  [...]
  "id": "55ce47fe015310754372d27d" // Student ID (Student's)
}
```

Despite the contents of the database at the time:
```sh
max@max-VirtualBox:/code/api$ sails console

info: Starting app in interactive mode...

[...]

undefined
sails> Student.find().exec(console.log);
undefined
sails> null [ { subGoals: [],
    createdAt: '2015-08-14T19:56:46.287Z',
    updatedAt: '2015-08-14T19:56:46.287Z',
    id: '55ce47fe015310754372d278' },
  { subGoals: [],
    createdAt: '2015-08-14T19:56:46.289Z',
    updatedAt: '2015-08-14T19:56:46.289Z',
    id: '55ce47fe015310754372d27a' },
  { subGoals: [],
    createdAt: '2015-08-14T19:56:46.291Z',
    updatedAt: '2015-08-14T19:56:46.291Z',
    id: '55ce47fe015310754372d27b' },
  { subGoals: [],
    createdAt: '2015-08-14T19:56:46.291Z',
    updatedAt: '2015-08-14T19:56:46.291Z',
    id: '55ce47fe015310754372d27c' },
  { subGoals: [],
    createdAt: '2015-08-14T19:56:46.292Z',
    updatedAt: '2015-08-14T19:56:46.292Z',
    id: '55ce47fe015310754372d27d' },
  { subGoals: [],
    createdAt: '2015-08-14T19:56:46.292Z',
    updatedAt: '2015-08-14T19:56:46.292Z',
    id: '55ce47fe015310754372d27e' },
  { subGoals: [],
    createdAt: '2015-08-14T19:56:46.292Z',
    updatedAt: '2015-08-14T19:56:46.292Z',
    id: '55ce47fe015310754372d27f' },
  { subGoals: [],
    createdAt: '2015-08-14T19:56:46.295Z',
    updatedAt: '2015-08-14T19:56:46.295Z',
    id: '55ce47fe015310754372d280' },
  { ipAssessment: '55d35010afb8db570b7c3e57',
    preferredCareer: '55ce47fe015310754372d21d',
    createdAt: '2015-08-14T19:56:46.289Z',
    subGoals: [],
    updatedAt: '2015-08-18T16:07:24.811Z',
    id: '55ce47fe015310754372d279' } ]

undefined
sails> Assessment.find().exec(console.log);
undefined
sails> null [ { student: '55ce47fe015310754372d279',
    survey: '55d34fbdafb8db570b7c3e1a',
    [...]
    resultData: {
        [...]
    },
    id: '55d35010afb8db570b7c3e57' } ]
```

**Comment by julienfouilhe** [comment]
I don't have any problems with the wrong association being retrieved when populating, but when creating a new model not associated to anything, it still retrieves something:

I have those two models: 

    // Book.js
    module.exports = {
    
      attributes: {
      	title: 'string',
        serie: { model: 'serie' }
      },
    
    };

    // Serie.js
    module.exports = {
    
      attributes: {
        name: 'string',
        books: { collection: 'book', via: 'serie' }
      }
    
    };


If I do this:

    $ sails console
    > Book.create({title: "Title"}).exec(function(err, book) {
        Book.findOne({id: book.id }).populateAll().exec(function(err, book) {
            console.log(book);
        });
    });

I get this:

    {
      serie: { name: 'Previously inserted serie' },
      title: 'Title',
      id: '55d6230122e3b1e70d877351'
    }

Why isn't serie empty ? When inserting the book, I didn't specify any serie but it is still linked to a random one.

**Comment by julienfouilhe** [comment]
Hi, it appears that the problem is coming from **waterline-cursor**. I made a pull request which fixes it but I don't know if anyone is working on this repository (last commit May, 2015).

https://github.com/balderdashy/waterline-cursor/pull/8

**Comment by anasyb** [comment]
>If you never added an assessment to that record and calling Survey.find().populate('assessment') returns a record for it then that's a huge problem but we have that stuff tested pretty well and I don't know of other related issues to that.

@particlebanana yes that's what happening here too, and indeed its big! The pull-request provided by @julienfouilhe does solve it. Can we get that merge ASAP please.

Same issue here https://github.com/balderdashy/sails-mongo/issues/320

cc @devinivy @dmarcelino

**Comment by tjwebb** [comment]
tests pass on https://github.com/balderdashy/waterline-cursor/pull/8; merged. 

@julienfouilhe @anasyb any thoughts on the best way to unit test this issue?
@particlebanana can you please publish a new version of waterline-cursor?
@mcodev1 can you replace the waterline-cursor in your mongo adapter with waterline-cursor/master and confirm the fix?

**Comment by devinivy** [comment]
@tjwebb @julienfouilhe do you understand the cause here?  I understand that the PR fixes it, but why are ghost foreign keys floating around in waterline-cursor?  Would this affect any adapter that relies on waterline-cursor for populates?

**Comment by julienfouilhe** [comment]
@devinivy
```javascript
Model.find({ id: undefined }).exec(console.log)
```
Returns no result. However

```javascript
Model.find({ where: { id: undefined } }).exec(console.log)
```
returns all results.

The reason for this is that `id` doesn't exist, as MongoDB names it `_id`. So every document has an `id` field undefined, hence why we get all of them. 

Criteria used by populate method is `{ where: { id: foreign_key } }`.

That's why I don't think my PR is really the best way to fix it, it goes deeper.

**Comment by tjwebb** [comment]
@julienfouilhe @devinivy this waterline-cursor strangeness only seems to manifest in mongo, right? I haven't seen any similar issues in sails-disk, though I could've just failed to connect the dots.

**Comment by anasyb** [comment]
@tjwebb can you do a release of waterline-curser to 0.0.6 so that sails-mongo gets fixed up

BTW this issue didnt even popup for me on mongo until very recently... I noticed that the same code started behaving differently

**Comment by julienfouilhe** [comment]
@tjwebb @devinivy Here are some unit tests that should fail for this. https://github.com/balderdashy/waterline-adapter-tests/blob/master/interfaces/associations/oneToOne/find.populate.js

If I'm right about the cause of the problem then yes it should only be happening in mongo, as it is the join criteria generation at fault.

**Comment by julienfouilhe** [comment]
@tjwebb @devinivy Replacing the following test:

```javascript
      it('should return a user object when the profile is undefined', function(done) {
        Associations.User_resource.create({ name: 'foobar', profile: undefined }).exec(function(err, usr) {
          assert(!err, err);

          Associations.User_resource.find({ name: 'foobar' })
          .populate('profile')
          .exec(function(err, users) {
            assert(!err);
            assert(users[0].name);
            assert(!users[0].profile, 'Expected `users[0].profile` to be falsy, but instead users[0] looks like ==> '+require('util').inspect(users[0], false, null));
            done();
          });
        });
      });
```
With this:

```javascript
      it('should return a user object when the profile is undefined', function(done) {
        Associations.User_resource.create({ name: 'foobar' }).exec(function(err, usr) {
          assert(!err, err);

          Associations.User_resource.find({ name: 'foobar' })
          .populate('profile')
          .exec(function(err, users) {
            assert(!err);
            assert(users[0].name);
            assert(!users[0].profile, 'Expected `users[0].profile` to be falsy, but instead users[0] looks like ==> '+require('util').inspect(users[0], false, null));
            done();
          });
        });
      });
```

Makes the test fail. Really tricky there!

So I don't really know how this is handled differently, I'll dig into it but you guys should do it as well as I don't know the code at all.

**Comment by julienfouilhe** [comment]
@tjwebb @devinivy Here are some unit tests that should fail for this. https://github.com/balderdashy/waterline-adapter-tests/blob/master/interfaces/associations/oneToOne/find.populate.js

If I'm right about the cause of the problem then yes it should only be happening in mongo, as it is the join's criteria generation at fault.

Replacing the following test:

```javascript
      it('should return a user object when the profile is undefined', function(done) {
        Associations.User_resource.create({ name: 'foobar', profile: undefined }).exec(function(err, usr) {
          // ...
          });
        });
      });
```
With this (I just removed the `profile: undefined` in the `.create` method):

```javascript
      it('should return a user object when the profile is undefined', function(done) {
        Associations.User_resource.create({ name: 'foobar' }).exec(function(err, usr) {
          // ...
          });
        });
      });
```

Makes the test fail. Really tricky there!

So I dug into it and I found out that when creating the model with `profile: undefined`, it actually replaced, upon creation in Mongodb, the field with `null`, which works as expected (i.e. doesn't return any document).

This is exactly what my PR was fixing, even though the following might be a nicer way:

 ```javascript
if(strategy === strategies.HAS_FK) {
    buffer.parentFK = parent[instructions.instructions[population].instructions[0].parentKey];
    if (buffer.parentFK === undefined) {
        buffer.parentFK = null;
    }
}

buffers.add(buffer);
```

**Comment by mcodev1** [comment]
Using `balderdashy/waterline-cursor` does fix the problem, thanks.

**Comment by julienfouilhe** [comment]
@tjwebb @particlebanana @anasyb Hi guys, just wondering when the fix is going to be released officially?

**Comment by mcodev1** [comment]
A release of waterline-cursor would be very helpful.

**Comment by devinivy** [comment]
CC @tjwebb @particlebanana ^^

**Comment by particlebanana** [comment]
@devinivy @mcodev1 done pushed out `0.0.6`

**Comment by Solskido** [comment]
@particlebanana Thanks Cody!

**Comment by mcodev1** [comment]
@particlebanana Thanks Cody!

**Comment by julienfouilhe** [comment]
@particlebanana Don't we need a new release of sails-mongo too?

**Comment by devinivy** [comment]
Yeah, we will.  Just upgraded this dependency in sails-mongo.
