### ISSUE TITLE
Global variable leak breaking build.

### ISSUE THREAD

**Issue by devinivy** [balderdashy/sails-mongo#330]
mongodb 2.0.36 and up leak `Promise` due to the es6-promise library being used, which loves to leak `Promise` (related: https://github.com/jakearchibald/es6-promise/pull/126).  The mongo driver does now take options to specify a different library, but I couldn't get it to work in all cases.  I tried using bluebird, since waterline is promisified using bluebird.

The other route is to accept that the mongodb driver leaks `Promise` by default, and to tell mocha to ignore that.  CC @tjwebb @dmarcelino

**Comment by devinivy** [comment]
I filed an issue with the driver https://jira.mongodb.org/browse/NODE-550

**Comment by japel** [comment]
@devinivy is this related to #300 and or #324 ?

**Comment by devinivy** [comment]
@japel I don't think so, though clearly the mongodb driver is causing us some pains right now.  Currently some new functionality in mongodb is breaking our tests because our tests require that no variables are leaked.  In this case the leak is harmless, but it's making it hard to evaluate PRs since it causes mocha to claim that the tests failed (even though the unit and integration tests may actually be fine).

**Comment by devinivy** [comment]
Fixed with #332
