### ISSUE TITLE
Very slow mongo queries?

### ISSUE THREAD

**Issue by robgrimball** [balderdashy/sails-mongo#331]
I am not sure if this is related to #330 and apologize in advance for a general lack of information, however, I ran into issues where the sail-mongo adapter, when dependencies were brought in was proving to perform extremely slow queries when used via waterline.  This was just doing a "npm install" with ~0.11.2 of sails-mongo.  Fortunately I had a shrinkwrap file from earlier when I wasn't having troubles, and while it was also using 0.11.2 of sails-mongo, it didn't exhibit this behavior, so I shrinkwrapped the entire app, and then replaced the dependencies section of the shrinkwrap file for sails-mongo with the one that I had from before(see below) which worked and this fixed the problems of the slow queries.

I am unfortunately in the midst of a deployment of the application so can not spend a lot of time hunting this down at the moment, but will provide the dependencies section that works here for me with sails-mongo.  To get the one that doesn't work(ie has the slow queries), just a fresh install and shrinkwrap will give you that.  

BTW: When I say slow queries, I mean a query that is nearly instant taking 50+ seconds to run, and to prove out that it had nothing to do with my code I ran the query straight through the blueprint endpoint to prove it was absolutely not related to my code at all.  The fact that this was the case is what tipped me off to looking into the earlier shrinkwrap where all was okay.

Again, apologies in advance for the lack of deeper info, but if someone experiences something similar, then perhaps the below will help them out.

```
      "dependencies": {
        "async": {
          "version": "0.8.0",
          "from": "https://registry.npmjs.org/async/-/async-0.8.0.tgz",
          "resolved": "https://registry.npmjs.org/async/-/async-0.8.0.tgz"
        },
        "mongodb": {
          "version": "2.0.39",
          "from": "https://registry.npmjs.org/mongodb/-/mongodb-2.0.39.tgz",
          "resolved": "https://registry.npmjs.org/mongodb/-/mongodb-2.0.39.tgz",
          "dependencies": {
            "mongodb-core": {
              "version": "1.2.6",
              "from": "https://registry.npmjs.org/mongodb-core/-/mongodb-core-1.2.6.tgz",
              "resolved": "https://registry.npmjs.org/mongodb-core/-/mongodb-core-1.2.6.tgz",
              "dependencies": {
                "bson": {
                  "version": "0.4.8",
                  "from": "https://registry.npmjs.org/bson/-/bson-0.4.8.tgz",
                  "resolved": "https://registry.npmjs.org/bson/-/bson-0.4.8.tgz"
                },
                "kerberos": {
                  "version": "0.0.12",
                  "from": "https://registry.npmjs.org/kerberos/-/kerberos-0.0.12.tgz",
                  "resolved": "https://registry.npmjs.org/kerberos/-/kerberos-0.0.12.tgz",
                  "dependencies": {
                    "nan": {
                      "version": "1.8.4",
                      "from": "https://registry.npmjs.org/nan/-/nan-1.8.4.tgz",
                      "resolved": "https://registry.npmjs.org/nan/-/nan-1.8.4.tgz"
                    }
                  }
                }
              }
            },
            "readable-stream": {
              "version": "1.0.31",
              "from": "https://registry.npmjs.org/readable-stream/-/readable-stream-1.0.31.tgz",
              "resolved": "https://registry.npmjs.org/readable-stream/-/readable-stream-1.0.31.tgz",
              "dependencies": {
                "core-util-is": {
                  "version": "1.0.1",
                  "from": "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.1.tgz",
                  "resolved": "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.1.tgz"
                },
                "isarray": {
                  "version": "0.0.1",
                  "from": "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz",
                  "resolved": "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz"
                },
                "string_decoder": {
                  "version": "0.10.31",
                  "from": "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz",
                  "resolved": "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz"
                },
                "inherits": {
                  "version": "2.0.1",
                  "from": "https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz",
                  "resolved": "https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz"
                }
              }
            },
            "es6-promise": {
              "version": "2.1.1",
              "from": "https://registry.npmjs.org/es6-promise/-/es6-promise-2.1.1.tgz",
              "resolved": "https://registry.npmjs.org/es6-promise/-/es6-promise-2.1.1.tgz"
            }
          }
        },
        "waterline-cursor": {
          "version": "0.0.5",
          "from": "https://registry.npmjs.org/waterline-cursor/-/waterline-cursor-0.0.5.tgz",
          "resolved": "https://registry.npmjs.org/waterline-cursor/-/waterline-cursor-0.0.5.tgz",
          "dependencies": {
            "async": {
              "version": "0.9.2",
              "from": "https://registry.npmjs.org/async/-/async-0.9.2.tgz",
              "resolved": "https://registry.npmjs.org/async/-/async-0.9.2.tgz"
            }
          }
        },
        "waterline-errors": {
          "version": "0.10.1",
          "from": "https://registry.npmjs.org/waterline-errors/-/waterline-errors-0.10.1.tgz",
          "resolved": "https://registry.npmjs.org/waterline-errors/-/waterline-errors-0.10.1.tgz"
        }
      }
```

**Comment by robgrimball** [comment]
Also, when I say a slow query, the query was also a very simple one, basically searching on a foreign key, and looks like this : 

https://localhost:1337/api/mymodel?where={%22user%22:%22541888cffc906893462d6e78%22}

In this case, mymodel is the model, and I am simply searching for all mymodels with a specific user ID.

**Comment by devinivy** [comment]
@robgrimball try locking-down the mongodb driver to a different version.  We observed a similar issue in #324 / #300, and there's a proposed solution in there.

**Comment by devinivy** [comment]
@robgrimball sounds like that worked for you in #300.  Can we close this out and leave #300 open until we determine the best course of action?

**Comment by robgrimball** [comment]
Sounds good, and yes.  I'll go ahead and close it now.  Thanks.

**Comment by devinivy** [comment]
@robgrimball it sounds like the latest version of mongodb has fixed this (https://github.com/balderdashy/sails-mongo/issues/324#issuecomment-137725267).  Do you mind trying 2.0.42 to verify?

**Comment by robgrimball** [comment]
@devinivy I did try it(mentioned that in #300 actually) and it did seem to clear up things.  I thought I was using that version before, but must not have been since it seems to all be working now.
