### ISSUE TITLE
Incorrect populate for empty field

### ISSUE THREAD

**Issue by Menjoy** [balderdashy/sails-mongo#333]
Please, read a question here http://stackoverflow.com/questions/32275320/association-populate-returns-results-even-if-an-association-is-empty

So I have the same problem.
Populate call gets first entry from the 'role'.

Setting of 'defaultTo: null' doesn't work too.

**Comment by devinivy** [comment]
Can you share your version of sails-mongo and waterline?  Also, it's worth seeing if your issue persists when using the latest version of sails-mongo and waterline.

**Comment by Menjoy** [comment]
So

{
 "name": "sails-mongo",
  "version": "0.11.2"
}

**Comment by devinivy** [comment]
@Menjoy please try the master branch of sails-mongo.  It includes a patch to waterline-cursor that may have caused this issue.

Related: https://github.com/balderdashy/sails/issues/3204 and https://github.com/balderdashy/waterline-cursor/issues/1

**Comment by Menjoy** [comment]
@devinivy thank you, it helped. Populate works correctly now.
