### ISSUE TITLE
[Question] Mock mongodb

### ISSUE THREAD

**Issue by jossemarGT** [balderdashy/sails-mongo#346]
Hello!

I'm trying to mock mongo database, in that way the test suite can run without any "real" database connection. Do you have any suggestion or am I missing something?

By the way, I was thinking to implement something similar to mockgoose. 

Thanks for your time. Happy coding :octocat:

**Comment by devinivy** [comment]
If you're using waterline and you need to use a mock adapter, try [sails-memory](https://github.com/balderdashy/sails-memory) or [waterline-sqlite3](https://github.com/waterlinejs/sqlite3-adapter).  sails-memory operates in schemaless mode, so it might be the better option.  Mocking waterline can also be done with a module called [weaselpecker](https://github.com/ottogiron/weaselpecker).  What do you have in mind to specifically mock a _mongodb_ database?

**Comment by jossemarGT** [comment]
Hi @devinivy you're right! I just want to check some model validations so sails-memory should do the trick! Thanks!
