### ISSUE TITLE
sails-mongo usage in session.js gives me an error

### ISSUE THREAD

**Issue by angel1st** [balderdashy/sails-mongo#355]
Hi there,
I would like to have persistent sessions and choose MongoDB for session store, since this DB is my project choice.
So I look at `config/session.js` and uncomment following lines:

       adapter: 'mongo',
       host: 'localhost',
       port: 27017,
       db: 'myDB',
       collection: 'sessions', 
I already have `sails-mongo` installed in my project, so I thought all is fine.

However, as long as I tried to lift the server, I have got following errors:

    error: A hook (`session`) failed to load!
    error: Could not load Connect session adapter :: connect-mongo

So my question is - why I cannot use already installed sails-mongo adapter for sessions?

If I miss something or you can tell me how to alter the code in order to start using `sails-mongo` instead of `connect-mongo` it would be nice.

Best Regards,
Angel

**Comment by devinivy** [comment]
Hi @angel1st– you might consider asking this in the sails.js issue tracker.  It might have something to do with the order that sails hooks get loaded.  There shouldn't be any such limitations originating from the sails-mongo adapter.

**Comment by angel1st** [comment]
OK, I will report it there.

Best Regards,
Angel

**Comment by devinivy** [comment]
Thanks and good luck!
