### ISSUE TITLE
'in' queries into 'or' clauses seems doesn't work

### ISSUE THREAD

**Issue by sbeluzo** [balderdashy/sails-mongo#361]
When querying like so: 
```
 Model.find()
 .where(criteria)
 .where( { or: [ { id : [1,2,3,4] }, { owner: someId } ] } )

```
The result is always [ ], although 1, 2, 3 and 4 exist and owner has the record with id 5.
There is a way to make this query in a single Find() or should I chain more than one Find()?

**Comment by devinivy** [comment]
This could have something to do with chaining multiple `where()`s.  I've never tried that, and I don't think it's tested.  What happens if you remove the first `where()`?

**Comment by sbeluzo** [comment]
You're right, But I still get a wrong result making this two queries:

```
 Model.find()
 .where( { or: [ { id : [1,2,3,4] }/*, { owner: someId }*/ ] } )
 .exec( function (err, result) {    } );
```
and 

```
 Model.find()
 .where( { id : [1,2,3,4] } )
 .exec( function (err, result) {    } );
```

The first one is what I wanna make and the result is [] when the correct would be [1,2,3,4,5], however the second one gives the records of [ 1, 2, 3, 4]. 

I suspect that "or" clause doesn't work with 'id' in array, but im not totally sure.

**Comment by devinivy** [comment]
I suggest popping a `console.log` around here to see just what's going on: https://github.com/balderdashy/sails-mongo/blob/master/lib/collection.js#L92

If you care to go through it, the logic that generates the queries is here: https://github.com/balderdashy/sails-mongo/blob/master/lib/query/index.js

**Comment by sbeluzo** [comment]
Problem Solved!
I didn't see anything weird in the code, I made a reinstall of sails-mongo and the problem disappeared. 

It was extrange because my sails-mongo was the same that the version reinstalled, anyways thank you very much for your time.
