### ISSUE TITLE
Finding model with nested ObjectId

### ISSUE THREAD

**Issue by pkarc** [balderdashy/sails-mongo#366]
Having Branches:

    Branch : {
        name: String
        business: {
            _id : ObjectId
        }
    }

Finding Branches:

    Branches.find({
                where : {
                    'business._id': new ObjectID(businessId)
                }
            }, function(err, branches){

                if(err) return res.json(err);

                if(!branches) return next();

                res.json(branches);

            }
    );

Instead of returning businessId branches, this returns all branches in the collection.

**Comment by devinivy** [comment]
From the docs,
> `sails-mongo` maps the logical `id` attribute to the required `_id` physical-layer mongo id.

Try using `id` rather than `_id`.  You wont have to define `id` explicitly in your collection definition.

**Comment by pkarc** [comment]
Thank you!  We just upgrade from v9
