### ISSUE TITLE
Query.parseValue turns strings into regex by default

### ISSUE THREAD

**Issue by charlietilt** [balderdashy/sails-mongo#383]
This is more of question, than an issue. Is there a particular reason that the `parseValue` method is turning string values into regular expressions? And is there a way to override this behavior on a per query basis?

Example:
`Movie.find {title: 'Super Troopers'}, (error, results) ->`

would yield the following query in mongo:
`query: { title: /^Super Troopers$/i }`

and would negate the benefit of having an index on that field
`planSummary: IXSCAN { title: 1 } ntoreturn:1000 ntoskip:0 nscanned:18745 nscannedObjects:10931 keyUpdates:0 numYields:0 locks(micros) r:72030 nreturned:1 reslen:4075 72ms`

If I do the following query manually/natively:
```
Movie.native (error, collection) ->
  collection.find({title: 'Super Troopers'}).toArray (error, results) ->
```
would yield the following query in mongo:
`query curation.listing query: { title: "Super Troopers" }`

and would negate the benefit of having an index on that field
`planSummary: IXSCAN { addressHash: 1 } ntoreturn:1000 ntoskip:0 nscanned:1 nscannedObjects:1 keyUpdates:0 numYields:0 locks(micros) r:142 nreturned:1 reslen:4075 0ms`

**Comment by particlebanana** [comment]
The regex is because Waterline's api expects queries to be case insensitive. This is a legacy from when mysql was the only adapter.

As of sails-mongo `0.12` you can enable/disable this on a per connection basis by adding the `wlNext` flag to your config:

```javascript
mongo: {
  module: 'sails-mongo',
  host: 'localhost',
  port: 27017,
  user: 'username'
  password: 'password',
  database: 'your mongo db name here',
  wlNext: {
    caseSensitive: false
  }
}
```
