### ISSUE TITLE
.populate() many to many fails on 0.12.0

### ISSUE THREAD

**Issue by kamek-pf** [balderdashy/sails-mongo#389]
Hey, here are my models : 
```
var Campaign = {
    attributes: {
        // ...
        challenges: { collection: 'Challenge', via: 'campaigns', dominant: true },
        // ...
};
```
and :
```
var Challenge = {
    attributes: {
        // ...
        campaigns: { collection: 'Campaign', via: 'challenges' },
        // ...
};
```

The actual query is sitting in an async function somewhere in my GraphQL backend, it looks like that :
```
return await Models.campaign.find().populate('challenges');
```

Now the weird thing is, it works fine with `sails-mongo@beta` (which is `0.10.0-rc5`), but not with `0.12.0`.
Here the stack trace : 
```
Error (E_UNKNOWN) :: Encountered an unexpected error
TypeError: Cannot read property '_getPK' of undefined
at StrategyPlanner._runJoins.$getPK (/my/local/path/node_modules/sails-mongo/lib/adapter.js:487:28)
...
```

Any idea what's going on ?

**Comment by kamek-pf** [comment]
Also, I tried a `await Models.campaign.find().populateAll();`, and it doesn't work with either versions.

**Comment by mikermcneil** [comment]
@kamek-pf not sure what's going on here-- spread a little too thin right now to track this down myself, but I did go ahead and add a couple of quick assertions to the code to improve the error message shown and assist with debugging.

**Comment by mikermcneil** [comment]
@kamek-pf would you mind including your Sails version (or waterline version if you're using that directly) as well as your version of Node?  Also if you could include your default model settings (`config/models.js`) and datastore configuration (`config/connections.js`), that'd be super helpful as well.  (and if your individual model defs explicitly point at particular datastores via `connection`, would you point that out?)

**Comment by kamek-pf** [comment]
@mikermcneil Sure !
I'm using Waterline directly, the models come from another backend using Sails, but this one isn't.
Anyways :
```
node --version
v5.7.1
```

This gist shows how I'm initializing the whole thing : https://gist.github.com/kamek-pf/a775902362c24d577fd2

Here's  the config (this is what's inside `dbConfig` in the gist): 
```
{
    "connections": {
        "mongo": {
            "adapter": "mongo",
            "host": "localhost",
            "port": 27017,
            "database": "myDbName"
        }
    }
}
```

It's really just the `.populate()` and `.populateAll()` methods that aren't working as they should.
Thanks for taking some time to look into this !

**Comment by kamek-pf** [comment]
Ok I have some progress on this.
Turns out my `identity` keys weren't lowercase. The docs explicitly say this is important but I missed that part somehow, my bad.
So now I can use `.populate()` properly, but `.populateAll()` still gives me this :
```
[TypeError: Cannot read property 'forEach' of undefined]
```

Will investigate.
Those assertions you added were really helpful btw, thanks a bunch !
